server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  data:
    redis:
      host: 122.51.165.51
      port: 6379
      password: xWBbAP7d2tSGdnES
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.165.51:8848
    gateway:
      routes:
        - id: feng-shortlink-admin
          uri: lb://feng-shortlink-admin/api/fenglink/v1/admin/**
          predicates:
            - Path=/api/fenglink/v1/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/fenglink/v1/admin/user/login
                  - /api/fenglink/v1/admin/user/has-username
                  - /api/fenglink/v1/admin/user
        - id: feng-shortlink-project
          uri: lb://feng-shortlink-project/api/fenglink/v1/**
          predicates:
            - Path=/api/fenglink/v1/**
          filters:
            - name: TokenValidate
