server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.187.101
      port: 6379
      password: 51213002
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1  # 表示已删除的值
      logic-not-delete-value: 0  # 表示未删除的值
