server:
  port: 8001
spring:
  application:
    name: feng-shortlink-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.187.101
      port: 6379
      password: 51213002
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.187.101:8848
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1  # 表示已删除的值
      logic-not-delete-value: 0  # 表示未删除的值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
short-link:
  stats:
    locale:
      amap-key: d8ff1fbaa0db78890a8659a25ace740f
  thread:
      max-retry-times: 5
      retry-interval-millis: 1000
  domain: "baidu.com:8001"
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
rocketmq:
  name-server: 192.168.187.101:9876  # RocketMQ NameServer 地址
  producer:
    group: shortlink-stats-producer-group  # 生产者组
  consumer:
    group: shortlink-stats-consumer-group  # 消费者组
